name: Deploy Docs
description: Copies generated docs to the web server

on:
  workflow_call:
    inputs:
      subdomain:
        required: true
        type: string
      source:
        required: true
        type: string
      site:
        required: true
        type: string
    secrets:
      WEBSERVER_IP:
        required: true
      WEBSERVER_USER:
        required: true
      WEBSERVER_SSH_PRIVATE_KEY:
        required: true
      WEBSERVER_SSH_PASSPHRASE:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create directory on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.WEBSERVER_IP }}
          username: ${{ secrets.WEBSERVER_USER }}
          key: ${{ secrets.WEBSERVER_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.WEBSERVER_SSH_PASSPHRASE }}
          script: mkdir -p /var/www/${{ inputs.site }}/subdomains/${{ inputs.subdomain }}

      - name: Copy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.WEBSERVER_IP }}
          username: ${{ secrets.WEBSERVER_USER }}
          key: ${{ secrets.WEBSERVER_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.WEBSERVER_SSH_PASSPHRASE }}
          source: ${{ inputs.source }}
          target: /var/www/${{ inputs.site }}/subdomains/${{ inputs.subdomain }}/
          strip_components: 1