name: Deploy to DigitalOcean

on:
  workflow_call:
    inputs:
      site_directory:
        description: Directory on server e.g. /var/www/cathe.dev
        required: true
        type: string
    secrets:
      SERVER_IP:
        required: true
      SERVER_USER:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      SSH_PASSPHRASE:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ${{ inputs.site_directory }}
            git pull origin main